### ISSUE TITLE
Create new InPynamo connection if loop is closed

### ISSUE THREAD

**Issue by johnssuh** [MyMusicTaste/InPynamoDB#8]
Currently, in the _get_connection(), new connection is established if there isn't a cached instance of TableConnection. However, this means that even when a new event loop is generated, the Model instances refer to the old connection which may have closed and therefore unable to perform any actions.
 
A hotfix would be to change the logic in the _get_connection() method to account for this. 
But I think this might really have to do with the "session" denoted by the session_cls keyword argument when creating TableConnection. Something more elaborate / smooth can be done with this.

**Comment by sunghyun-lee** [comment]
In this time, I have doubt that session is successfully closing, since I can't assure `__del__()` is called appropriately. I should fix this first, and we have to see same error is still occurring.
The fix for that is still, complicated to implement.

I am considering to apply 'context manager' to dispatch or _make_api_call, and session closing will be done by aiobotocore's client, not our AsyncConnection class. I will let you know when implementation is done.

**Comment by sunghyun-lee** [comment]
updated on https://github.com/MyMusicTaste/InPynamoDB/commit/1885e198294f2968d50a8c07a100c686e2f47b5d

need to check if it is working.

**Comment by sunghyun-lee** [comment]
closed 8d21e1fc5085d2ee95a20317fcca7afca55c8b44
